"""GoldRush deterministic simulation and official strategy ABI package."""

from .abi import (
    CallableStrategy,
    DecisionCall,
    GameInput,
    GameOutput,
    NpcInfo,
    SharedObjectStrategy,
    StayStrategy,
    StrategyError,
    StrategyExecutionError,
    StrategyLoadError,
    StrategyOutputError,
    player_input_to_abi,
    validate_output,
    verify_abi_layout,
)
from .runner import (
    DEFAULT_DISPATCH,
    DEFAULT_FIXED_COSTS,
    DISPATCH_MODES,
    GameResult,
    PairedResult,
    RunnerError,
    ScriptedStrategy,
    StrategyForfeit,
    load_map,
    paired_summary,
    round_log_record,
    run_game,
    run_paired,
)

__all__ = [
    "CallableStrategy",
    "DecisionCall",
    "GameInput",
    "GameOutput",
    "NpcInfo",
    "SharedObjectStrategy",
    "StayStrategy",
    "StrategyError",
    "StrategyExecutionError",
    "StrategyLoadError",
    "StrategyOutputError",
    "player_input_to_abi",
    "validate_output",
    "verify_abi_layout",
    "DEFAULT_DISPATCH",
    "DEFAULT_FIXED_COSTS",
    "DISPATCH_MODES",
    "GameResult",
    "PairedResult",
    "RunnerError",
    "ScriptedStrategy",
    "StrategyForfeit",
    "load_map",
    "paired_summary",
    "round_log_record",
    "run_game",
    "run_paired",
]
